version: '3.8'
services:
  db:
    build: .
    container_name: foodies_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: foodies
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: password

volumes:
  pgdata:
